"""Infrastructure-free domain models used by the evidence-first import pipeline."""

from arduino_component_kb.imports.pipeline.models.artifact import SourceArtifact
from arduino_component_kb.imports.pipeline.models.component_identity import (
    CategoryCandidate,
    ComponentIdentity,
    ComponentKind,
    IdentityAlias,
    IdentityConfidence,
    IdentityResolutionStatus,
    IdentityValue,
    KindCandidate,
    ScoreContribution,
)
from arduino_component_kb.imports.pipeline.models.extracted_facts import (
    DescriptionSection,
    ExtractedFacts,
    ExtractedField,
    Identifier,
    IdentifierKind,
    ImageReference,
    ModulePin,
    RawSpecification,
    ResourceKind,
    ResourceReference,
    UnknownFact,
)
from arduino_component_kb.imports.pipeline.models.kicad import (
    KicadCandidateSet,
    KicadEnrichmentRequest,
    KicadMatchBasis,
    KicadMatchedTerm,
    KicadPin,
    KicadSearchHit,
    KicadSymbolIndex,
    KicadSymbolRecord,
)
from arduino_component_kb.imports.pipeline.models.normalized_facts import (
    NormalizationConfidence,
    NormalizationConflict,
    NormalizationProfile,
    NormalizationTrace,
    NormalizedFacts,
    NormalizedIdentifier,
    NormalizedSpecification,
    NormalizedTextFact,
    UnmappedSpecification,
)
from arduino_component_kb.imports.pipeline.models.provenance import (
    EvidenceFragment,
    ExtractionWarning,
    SourceArtifactMetadata,
    SourceReference,
)

__all__ = [
    "CategoryCandidate",
    "ComponentIdentity",
    "ComponentKind",
    "DescriptionSection",
    "EvidenceFragment",
    "ExtractedFacts",
    "ExtractedField",
    "ExtractionWarning",
    "Identifier",
    "IdentifierKind",
    "IdentityAlias",
    "IdentityConfidence",
    "IdentityResolutionStatus",
    "IdentityValue",
    "ImageReference",
    "ModulePin",
    "KindCandidate",
    "KicadCandidateSet",
    "KicadEnrichmentRequest",
    "KicadMatchBasis",
    "KicadMatchedTerm",
    "KicadPin",
    "KicadSearchHit",
    "KicadSymbolIndex",
    "KicadSymbolRecord",
    "NormalizationConfidence",
    "NormalizationConflict",
    "NormalizationProfile",
    "NormalizationTrace",
    "NormalizedFacts",
    "NormalizedIdentifier",
    "NormalizedSpecification",
    "NormalizedTextFact",
    "RawSpecification",
    "ResourceKind",
    "ResourceReference",
    "ScoreContribution",
    "SourceArtifact",
    "SourceArtifactMetadata",
    "SourceReference",
    "UnknownFact",
    "UnmappedSpecification",
]
